### ISSUE TITLE
Getting "Burrow Server: Error" in UI

### ISSUE THREAD

**Issue by k1ng87** [GeneralMills/BurrowUI#1] opened 2017-04-12 18:23 UTC
I'm getting a `Burrow Server: Error` in the top right of the UI when I launch it but don't know why. Burrow is up and I can hit the end point but is there a way to figure out why I'm getting that error?

When I start BurrowUI, I get this:

```
usrxxx$ node server.js
BURROW_HOME: undefined
Burrow Home Not Set
url is now:  http://myip:9050/v2/kafka/
API running on localhost:3000
```

I modified this:

```
else {
  console.log("Burrow Home Not Set");
  burrow_url = config.burrow.home;
}
```

to this:

```
else {
  console.log("Burrow Home Not Set");
  burrow_url = config.burrow.home;
  console.log("url is now: ", burrow_url);
}
```

to make sure `burrow_url` is getting set...

my server_config.json looks like this:

```
{
  "burrow" : {
    "home" : "http://myip:9050/v2/kafka/"
  }
}
```

and I've also tried this:

```
{
  "burrow" : {
    "home" : "http://myip:9050/v2/kafka"
  }
}
```

**Comment by cgosiak** [comment] 2017-04-13 12:15
@k1ng87  Perhaps it is an issue retrieving the data from Burrows API endpoints. Does the console log in your browser give any errors?

My first thought would be to check that out; Angular would most likely spout off some errors in the event that the UI is trying to access a parameter from a null object.'

For some extra logging:
If you want to add some console logging to the file src/app/services/burrow.service.ts
I would suggest right below line 32: and maybe try the following =>
console.log("My Burrow Host: " + obj.request.host);

**Comment by k1ng87** [comment] 2017-04-13 12:22
So what I found was at the api end calls, have `/cluster/` in them and I don't believe that is correct,,,the end points look like this `hostname:port//v2/kafka`. I removed that and I seemed to get data, but now I'm getting an error in the components now...

**Comment by cgosiak** [comment] 2017-04-13 14:33
The getHome function will serialize the home endpoint (server side) found. This can be found on LinkedIn's page: [Http Request List Clusters](https://github.com/linkedin/Burrow/wiki/http-request-list-clusters)

Are you on the newest version of Burrow?

Also, when you go to http://{your-url}/v2/kafka in a browser: What does the endpoint respond with? It should look similar to this:
{
  error: false,
  message: "cluster list returned",
  clusters: [
    "Sandbox",
    "Development",
    "Production"
  ],
  request: {
    url: "/v2/kafka",
    host: "your-host",
    cluster: "",
    group: "",
    topic: ""
  }
}

**Comment by cgosiak** [comment] 2017-04-25 13:06
@k1ng87 Does this seem to be where the issue is stemming from for you?

I am looking at closing the issue if this was the resolution.

**Comment by k1ng87** [comment] 2017-04-25 13:10
yep...I'm having trace back through all the api calls and data flows to get the graphs to work... I Haven't gotten through most of them but haven't really been focusing on it in a couple of weeks...

**Comment by cgosiak** [comment] 2017-05-11 13:36
@k1ng87 I am going to be closing this issue due to inactivity and my inability to reproduce the error. Feel free to reopen an issue if more data becomes available to you.

**Closed by cgosiak** 2017-05-11 13:36 UTC

**Comment by adomenech73** [comment] 2017-10-13 13:52
I have exactly the same issue as @k1ng87

Last version of Burrow running properly
Last version of BurrowUI
Build with @angular/cli 1.4.3 and  typescript 2.1

When I access via curl to Burrow endpoint I get:

```
curl http://localhost:8000/v2/kafka
{"error":false,"message":"cluster list returned","clusters":["local"],"request":
{"url":"/v2/kafka","host":"stg-backend-monitor-server-node0","cluster":"","group":"","topic":""}}
```
And also having this messages:
```
BURROW_HOME: undefined
Burrow Home Not Set
```
On burrowui log file

**Comment by adomenech73** [comment] 2017-10-16 07:42
After doing some tests I'm convinced that must be some kind of problem with build process.

@cgosiak Can you please give me some advice about which versions of angular/cli and type script would.be prefered? I finally get it builded forcing @angular/cli=1.4.3 and typescript=2.1 but probably the problem could be there.

The thing is that any time I restart BurrowUI I get:

```Bash
BURROW_HOME: undefined
Burrow Home Not Set
API running on 0.0.0.0:3000
```

Doesn't matter if I have a server_config.json created or even if I define the var on my environment like ```export BURROW_HOME=http://localhost:8000/v2/kafka``` I always get the same error message. I confirmed with tcpdump that communication between burrowi and burrow never starts

**Comment by adomenech73** [comment] 2017-10-16 10:12
Please forgive and forgot this lasts comments
I finally get it working, as messages where clearly saying the problem was with environment variables, and supervisor syntax to load them. Once this was solved everything's just works fine json config file is not needed and nothing to do with angular/cli version. Dependencies as in package.json just worked fine. sorry for that

**Comment by cgosiak** [comment] 2017-10-16 13:21
No worries, 
Something of note, is that there are some documented issues pointing to versioning problems. I am hoping to address this soon.

**Comment by balarampuli** [comment] 2018-05-06 23:45
Please share the fix if available, what needs to be updated to resolve that issue.

**Comment by budibong** [comment] 2019-07-09 10:36
i got same issue here 

request http://localhost:8000/v3/kafka return this : 
{"error":false,"message":"cluster list returned","clusters":["local"],"request":{"url":"/v3/kafka","host":"65deb9b12e98"}}

but when open localhost:3000 from browser i got this : 
Burrow Server : error
